config/routes.rb
ChristmasElf::Application.routes.draw do
  resources :people do
    collection do
      get 'next'
    end

    get 'opened', on: :member
  end

end

app/models/person.rb
class Person < ActiveRecord::Base

  after_initialize :defaults, :if => :new_record?

  def defaults
    self.gifts ||= 0
    self.quickies ||= 0
    self.smfls ||= 0
    self.opened ||= 0
  end

  def self.find_next

    gift_array = []
    Person.all.each do |person|
      person.remaining_gifts.times do
        gift_array << person
      end
    end

    gift_array.sample
  end

  def self.total_all_gifts
    people = Person.all
    gifts_set = Hash[people.collect { |person| [person.id, person.total_gifts] }]
    gifts_set.values.reduce(0,:+)
  end

  def self.total_all_opened
    people = Person.all
    gifts_set = Hash[people.collect { |person| [person.id, person.opened] }]
    gifts_set.values.reduce(0,:+)
  end

  def self.total_percent_opened
    100.0 * total_all_opened / total_all_gifts
  end

  def total_gifts
    gifts + quickies + smfls
  end

  def open_gift
    self.opened += 1
    self.save
  end

  def remaining_gifts
    return [total_gifts - opened, 0].max
  end

  def percent_opened
    100.0 * self.opened / total_gifts
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render action: 'show', status: :created, location: @person }
      else
        format.html { render action: 'new' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  def next
    @people = Person.all
    @selected = Person.find_next
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url }
      format.json { head :no_content }
    end
  end

  def opened
    opener = Person.find(params[:id])
    opener.open_gift
    redirect_to :action => :next
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :gifts, :quickies, :smfls, :opened)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ChristmasElf</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'>

<%= yield %>

</body>
</html>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :gifts %><br>
    <%= f.number_field :gifts %>
  </div>
  <div class="field">
    <%= f.label :quickies %><br>
    <%= f.number_field :quickies %>
  </div>
  <div class="field">
    <%= f.label :smfls %><br>
    <%= f.number_field :smfls %>
  </div>
    <div class="field">
      <%= f.label :opened %><br>
      <%= f.number_field :opened %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<h1>Listing people</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Gifts</th>
      <th>Quickies</th>
      <th>SMFLs</th>
      <th>Opened</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.gifts %></td>
        <td><%= person.quickies %></td>
        <td><%= person.smfls %></td>
        <td><%= person.opened %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<table>
  <thead>
    <tr>
      <th>Total Gifts</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= Person.total_all_gifts %></td>
    </tr>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>
<%= link_to 'Next Present!', :action => :next %>

app/views/people/new.html.erb
<h1>New person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/next.html.erb
<h1>Next Present: <%= @selected.name || "All presents opened!" %>!</h1>
<h1><%= "  JOKER!!" if(Random.new.rand(100) < 11) %></h1>
<h2><%= link_to "Open #{@selected.name}'s Gift!", opened_person_path(@selected) %> </h2>
<br>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Gifts</th>
      <th>Opened</th>
      <th>Complete</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.total_gifts %></td>
        <td><%= person.opened %></td>
        <td><%= "#{person.percent_opened.round(1)}%" %></td>
        <td><%= link_to 'Open a Gift!', opened_person_path(person) %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<h2><%= "Opened #{Person.total_all_opened}/#{Person.total_all_gifts}: #{Person.total_percent_opened.round(1)}%" %> </h2>
<br>


<br>
<%= link_to 'Next Present!', :action => :next %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Gifts:</strong>
  <%= @person.gifts %>
</p>

<p>
  <strong>Quickies:</strong>
  <%= @person.quickies %>
</p>

<p>
  <strong>SMFLs:</strong>
  <%= @person.smfls %>
</p>

<p>
  <strong>Opened:</strong>
  <%= @person.opened %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>